about-code/glossarify-md

README.md, lib/dictionary.js, lib/glossarify.js, lib/linker.js, lib/linkify.js, lib/term.js, lib/terminator.js, lib/writer.js, test/output-expected/markdown/html.md, test/output-expected/markdown/list.md, test/output-expected/markdown/text.md, test/output-expected/paths/sub-1/sub-2/deeply_nested.md, test/package.json
=> Option to add inline title attribute markdown link

doc/vuepress.md
=> Provide example for use with vuepress

.npmignore, lib/linker.js, lib/linkify.js, lib/term.js, package.json, test/input/features/i18n/document_de.md, test/input/features/i18n/glossary_de.md, test/input/glossarify-md.conf.json, test/output-expected/features/i18n/document_de.md, test/output-expected/features/i18n/glossary_de.md, test/output-expected/glossarify-md.conf.json, test/output-expected/terms.json
=> 28 terms with leading or trailing non-ASCII chars not linked

CHANGELOG.md, CONTRIBUTING.md, README.md, lib/linker.js, test/input/config-tailored/config-glossaries/glossarify-md.conf.json, test/input/config-tailored/config-glossaries/term-hint-document.md, test/input/config-tailored/config-glossaries/term-hint-prefix-glossary.md, test/input/config-tailored/config-glossaries/term-hint-suffix-default-glossary.md, test/input/config-tailored/config-glossaries/term-hint-suffix-glossary.md, test/input/config-tailored/config-glossaries/term-hint-wrapped-glossary.md, test/output-expected/config-tailored/config-glossaries/glossarify-md.conf.json, test/output-expected/config-tailored/config-glossaries/term-hint-document.md, test/output-expected/config-tailored/config-glossaries/term-hint-prefix-glossary.md, test/output-expected/config-tailored/config-glossaries/term-hint-suffix-default-glossary.md, test/output-expected/config-tailored/config-glossaries/term-hint-suffix-glossary.md, test/output-expected/config-tailored/config-glossaries/term-hint-wrapped-glossary.md, test/output-expected/config-tailored/config-glossaries/terms.json
=> 10 option to let user define position of term hint

CHANGELOG.md, lib/linkify.js, package-lock.json, package.json, test/input/config-shared/markdown/link.md, test/output-expected/config-shared/markdown/link.md
=> 37 glossary terms flanked by braces not linked

CHANGELOG.md, README.md, conf.schema.json, doc/vuepress.md, lib/linker.js, lib/terminator.js, test/input/config-shared/glossarify-md.conf.json, test/input/config-shared/markdown/footnotes.md, test/output-expected/config-shared/glossarify-md.conf.json, test/output-expected/config-shared/markdown/footnotes.md
=> 38 footnotes stop working when using glossarify

CHANGELOG.md, lib/term.js, package-lock.json, package.json, test/input/config-shared/aliases_and_synonyms/aliases_and_synonyms.md, test/input/config-shared/aliases_and_synonyms/glossary.md, test/output-expected/config-shared/aliases_and_synonyms/aliases_and_synonyms.md, test/output-expected/config-shared/aliases_and_synonyms/glossary.md, test/output-expected/config-shared/terms.json
Closes #41 Aliases not working.
=> 41 aliases not working

.gitignore, CONTRIBUTING.md, README.md, conf.schema.json, lib/glossarify.js, lib/linker.js, lib/messages.js, lib/term.js, lib/writer.js, package.json, test/output-expected/config-shared/terms.json, test/output-expected/config-tailored/config-baseUrl/terms.json, test/output-expected/config-tailored/config-excludeFiles/terms.json, test/output-expected/config-tailored/config-glossaries/terms.json, test/output-expected/config-tailored/config-ignoreCase-false/terms.json, test/output-expected/config-tailored/config-ignoreCase-true/terms.json, test/output-expected/config-tailored/config-linking/absolute-baseUrl/terms.json, test/output-expected/config-tailored/config-linking/relative/terms.json
=> 43 inform about terms not mentioned in text

.github/workflows/tests.yml, lib/linker.js, lib/terminator.js, test/output-expected/config-shared/aliases_and_synonyms/glossary.md, test/output-expected/config-shared/markdown/glossary.md, test/output-expected/config-shared/term_descriptions/glossary.md, test/output-expected/config-tailored/config-glossaries/disjunct-terms-glossary-a.md, test/output-expected/config-tailored/config-glossaries/disjunct-terms-glossary-b.md, test/output-expected/config-tailored/config-glossaries/shared-terms-glossary-a.md, test/output-expected/config-tailored/config-glossaries/shared-terms-glossary-b.md, test/output-expected/config-tailored/config-glossaries/terms.json, test/output-expected/config-tailored/config-glossaries/unicode-glossary.md, test/output-expected/config-tailored/config-indexFile/glossary-in-subdir/index.md, test/output-expected/config-tailored/config-indexFile/glossary-in-subdir/sub/glossary.md, test/output-expected/config-tailored/config-indexFile/index-in-subdir/glossary.md, test/output-expected/config-tailored/config-indexFile/index-in-subdir/sub/index.md, test/output-expected/config-tailored/config-indexFile/term-link-to-section/glossary.md, test/output-expected/config-tailored/config-indexFile/term-link-to-section/index.md, test/output-expected/config-tailored/count-term-occurrences/glossary.md, test/output-expected/config-tailored/count-term-occurrences/terms.json, test/output-expected/config-tailored/glossary-crosslinks/glossary-g1.md, test/output-expected/config-tailored/glossary-crosslinks/glossary-g2.md, test/output-expected/config-tailored/glossary-crosslinks/terms.json, test/output-expected/config-tailored/substring_behavior/glossary.md, test/output-expected/config-tailored/substring_behavior/terms.json
=> 50 linkify term usage in term definitions

lib/indexer.js, test/output-expected/config-indexFile/glossary-in-subdir/index.md, test/output-expected/config-indexFile/index-in-subdir/sub/index.md, test/output-expected/config-indexFile/multiple-glossaries/index.md, test/output-expected/config-indexFile/term-link-to-section/index.md
=> 64 index term headings should be at depth 2

README.md, conf.schema.json, lib/ast/tools.js, lib/index/figures.js, lib/index/tables.js, lib/indexer.js, lib/main.js, lib/reader.js, lib/writer.js, test/input/config-listOfTables/glossarify-md.conf.json, test/input/config-listOfTables/glossary.md, test/input/config-listOfTables/table-label-comment/table-label-comment.md, test/input/config-listOfTables/table-label-file/table-label-file.md, test/input/config-listOfTables/table-label-heading/table-label-heading.md, test/input/config-listOfTables/table-label-text/table-label-text.md, test/output-expected/config-indexing/groupByHeadingDepth-0/figures.md, test/output-expected/config-indexing/groupByHeadingDepth-0/index.md, test/output-expected/config-listOfTables/glossarify-md.conf.json, test/output-expected/config-listOfTables/glossary.md, test/output-expected/config-listOfTables/table-label-comment/table-label-comment.md, test/output-expected/config-listOfTables/table-label-file/table-label-file.md, test/output-expected/config-listOfTables/table-label-heading/table-label-heading.md, test/output-expected/config-listOfTables/table-label-text/table-label-text.md, test/output-expected/config-listOfTables/tables.md, test/package.json
=> 62 generate list of tables

lib/ast/tools.js, lib/terminator.js, test/input/config-glossaries/formatted-terms-document.md, test/input/config-glossaries/formatted-terms-glossary.md, test/input/config-glossaries/glossarify-md.conf.json, test/input/term-descriptions/document.md, test/input/term-descriptions/glossary.md, test/output-expected/config-glossaries/formatted-terms-document.md, test/output-expected/config-glossaries/formatted-terms-glossary.md, test/output-expected/config-glossaries/glossarify-md.conf.json, test/output-expected/config-glossaries/terms.json, test/output-expected/term-descriptions/document.md, test/output-expected/term-descriptions/glossary.md, test/output-expected/term-descriptions/terms.json
=> 81-82-be-more-tolerant-and-robust-with-markdown-formattings

lib/ast/tools.js, test/input/config-listOf/document-infer-label.md, test/output-expected/config-listOf/document-infer-label.md, test/output-expected/config-listOf/list-of-label.md
=> 84 extract anchor labels with markdown formatting

README.md
=> README: Fix json trailing comma

CHANGELOG.md, bin/index.js, lib/cli/messages.js, package-lock.json, package.json
=> 103 force flag not working

README.md, doc/templates/README.md, lib/ast/linkify.js, test/output-expected/markdown/html.md, test/output-expected/markdown/terms.json
=> 110 linkification in embedded html

lib/reader.js, package-lock.json, package.json, test/input/markdown-extensions/112-custom-header-id.md, test/output-expected/markdown-extensions/112-custom-header-id.md
=> 112 support pandoc style custom heading ids

lib/cli/upgrade/v4to5.js, lib/index/terms.js, test/input/config-indexFiles/154-deep-dir/document.md, test/input/config-indexFiles/154-deep-dir/glossarify-md.conf.json, test/output-expected/config-indexFiles/154-deep-dir/document.md, test/output-expected/config-indexFiles/154-deep-dir/glossarify-md.conf.json, test/output-expected/config-indexFiles/154-deep-dir/sub1-index/index-b.md, test/output-expected/config-indexFiles/154-deep-dir/sub1-index/sub2-index/index-c.md
=> 156 option indexfiles incorrect path from index to section of occurrence

CHANGELOG.md, lib/cli/messages.js, lib/cli/upgrade.js, package-lock.json, package.json
Only ask to install when configuration needs an upgrade.
=> Feat make inquirer a peer dependency.

bin/index.js, doc/README.md, doc/markdown-syntax-extensions.md, doc/plugins.md, doc/vuepress.md, md/doc/README.md, md/doc/markdown-syntax-extensions.md, md/doc/plugins.md, md/doc/vuepress.md
=> fix: --init --new wrongly assumes ./docs/glossary.md exists

README.md, bin/index.js, conf/README.md, lib/ast/with/term-definition.js, lib/cli/upgrade.js, lib/counter.js, lib/exporter.js, lib/index/terms.js, lib/indexer.js, lib/model/context.js, lib/sorter.js, lib/text/tools.js, lib/writer.js, md/README.md, md/doc/README.md, md/doc/cli.md, md/doc/glossary.md, md/doc/use-with-vuepress.md, package-lock.json, package.json, test/package.json, test/path-tools.spec.js, test/text-tools.spec.js
=> feat: watch mode

bin/index.js
=> fix: New config refers to outdated config release version

lib/terminator.js, test/input/markdown/glossary.md, test/output-expected/markdown/glossary.md
=> 257 fix empty header defect

CHANGELOG.md, conf/v5/schema.json, lib/ast/with/term-occurrence-node.js, package-lock.json, package.json, test/output-expected/config-cli/arg-init/minimal.conf.json, test/output-expected/config-cli/arg-init/more.conf.json, test/package-lock.json
=> 262 type error cannot convert a symbol to a string
